### PR TITLE
Async.bindChoice, AsyncSeq.zipWithAsync, AsyncSeq.merge, etc

### PR DESCRIPTION
**Pull request by eulerfx**
- Async.bindChoice
- Async.ParallelIgnore
- AsyncSeq.zipWithAsync
- AsyncSeq.zappAsync
- AsyncSeq.threadStateAsync
- AsyncSeq.merge
- AsyncSeq.traverseOptionAsync
- AsyncSeq.traverseChoiceAsync

### CODE REVIEW

**Comment by eulerfx** [comment]
Any thoughts on this one? @forki @tpetricek

**Comment by forki** [comment]
I'm not really the person to decide here. I'd like to see someone else to
become the maintainer. i just extracted the project from fsharpx.

2015-03-24 14:50 GMT+01:00 Lev Gorodinski notifications@github.com:

**Comment by eulerfx** [comment]
Cool, I won't bug you as much then :) I'd be more than happy to maintain, but it would be great to get input here and there initially. In particular, when introducing new concepts its worth getting a few eyes on it. Moreover, I think a filter is needed for some of the more opinionated stuff.

**Comment by forki** [comment]
@eulerfx what's your nuget name?

**Comment by eulerfx** [comment]
@forki eulerfx

**Pull request merged**
