### PR TITLE
NetStandard 2.0 support

### LINKED ISSUE #42: .NET Standard
Would be nice if this package was .NET Standard compatible

### PR DESCRIPTION
**Pull request by alex-bogomaz**
This library depends on "FSharp.Control.AsyncSeq",
so we need to wait for this PR to be merged https://github.com/fsprojects/FSharp.Control.AsyncSeq/pull/72
and https://github.com/fsprojects/FSharp.Control.AsyncSeq/issues/66 issue resolved.

After this there will be "FSharp.Control.AsyncSeq" for NetStandard 2.0 and we can proceed with this PR.

closes #42

### CODE REVIEW

**Comment by alex-bogomaz** [comment]
using 2.0.19 version of "FSharp.Control.AsyncSeq", which is for NetStandard 2.0.

Now PR is ready for review

**Comment by panesofglass** [comment]
@fsprojectsgit or @forki, can one of you please merge this?

**Comment by sergey-tihon** [comment]
@panesofglass I've fixed your credentials, so you merge PR.
You are in maintainers list but for some reason did not have enough right here.

**Comment by panesofglass** [comment]
@alex-bogomaz, thank you for this PR. Would you be willing to make some changes, similar to those offered in #43? Specifically, I'm thinking of the following changes:

- [ ] Use multi-targeting rather than separate `.sln` and `.fsproj` files
- [ ] Use the built-in [SourceLink](https://github.com/dotnet/sourcelink#using-source-link-in-net-projects) rather than retaining the old version

**Comment by panesofglass** [comment]
Merged into #44

**Comment by panesofglass** [comment]
Re-opening as the tracking PR. Thanks again, @alex-bogomaz!

**Comment by panesofglass** [comment]
@fsprojectsgit or @forki, could you publish 1.14.1 to NuGet or grant me access to publish this package?

**Comment by sergey-tihon** [comment]
@panesofglass it is already pending your approval
NuGet_Gallery___Manage_Package_FSharpx_Async

**Comment by panesofglass** [comment]
I missed that. I accepted, but I still cannot push for some reason.

**Pull request merged**
