### PR TITLE
Support netstandard2.0

### LINKED ISSUE #42: .NET Standard
Would be nice if this package was .NET Standard compatible

### PR DESCRIPTION
**Pull request by panesofglass**
Draws from #38 and #43 and closes #42

### CODE REVIEW

**Comment by panesofglass** [comment]
Need help fixing the travis build

**Comment by alex-bogomaz** [comment]
@panesofglass -I'll take a look at failing build

**Comment by panesofglass** [comment]
@alex-bogomaz want me to close this PR and submit the changes to your repo and reopen yours? Wasn’t sure initially if you were still pursuing this after so long. Apologies again for the delay.

**Comment by panesofglass** [comment]
Submitted PR https://github.com/alex-bogomaz/FSharpx.Async/pull/3. Closing this and re-opening #38

**Pull request closed without merging**
