### PR TITLE
add ParallelWithTrottle

### PR DESCRIPTION
**Pull request by sideeffffect**

### CODE REVIEW

**Comment by forki** [comment]
can you please split the build changes from the lib changes?

**Comment by sideeffffect** [comment]
done :wink:  sorry for the delay, I couldn't find the time during the week

**Comment by tpetricek** [comment]
Looks good to me.

**Comment by forki** [comment]
@tpetricek could you please take a look at master. I updated AsyncSeq and now it doesn't compile anymore

**Comment by tpetricek** [comment]
@forki Hopefully #32 will fix things!

**Pull request merged**
