### PR TITLE
Add Async.Any (amb) operator

### PR DESCRIPTION
**Pull request by panesofglass**
This was [first suggested by @haf](https://github.com/freya-fs/freya/pull/68#issuecomment-75705528).

### CODE REVIEW

**Comment by forki** [comment]
ready to merge?

**Comment by panesofglass** [comment]
No. For one, the Travis build broke b/c the error message differs (puncutation, `.` on .NET, no `.` on mono). Secondly, @eulerfx makes a great point. @tpetricek's original implementation may also be better: https://github.com/panesofglass/fsharpx/blob/asyncex/src/FSharpx.Core/Async.fs#L56-101. @tpetricek's implementation differs by when it returns an `Exception`. I was unsure of the correct or desired semantics here.

**Comment by panesofglass** [comment]
Should we add `chooseBoth`?

**Comment by panesofglass** [comment]
I was planning to add the rest of @tpetricek's extensions in a follow-up PR. If we want to use them, I can add them in now. It also includes a `Merge` extension. Should we add both options, `Choose` + `Merge` and `ChooseBoth` + `MergeBoth`?

**Comment by eulerfx** [comment]
I was planning to add `chooseBoth` but any thoughts on naming? I searched Hoogle for something comparable, but couldn't find anything.

WRT `Merge`, I recently added `Async.Parallel : Async<'a> * Async<'b> -> Async<'a * 'b>` which I believe has the same meaning. Perhaps it should be renamed to `Merge`?

**Comment by panesofglass** [comment]
@eulerfx, yes, I think that is `Merge`, at least from the implementations I've seen. I could very well be wrong.

**Comment by eulerfx** [comment]
I also wonder if it is worth highlighting the fact that use of `TaskCompletionSource` changes the semantics of `Async` - usually an `Async` is a computation which can be run repeatedly for its side-effects. If it comes from `TaskCompletionSource` however, it gets memoized. In these cases it is likely the desired behavior, but might be worth noting.

**Comment by forki** [comment]
please rebase this PR

**Comment by panesofglass** [comment]
I'm going to close it. I'll probably re-submit using @tpetricek's original code.

**Pull request closed without merging**
