### PR TITLE
Convert to multitarget netstandard2.0 + net45

### PR DESCRIPTION
**Pull request by Szer**
I've tried to convert whole process to modern way:
  * Added multi target build:
    * old net45 dependencies lives under Legacy build group
  * Integrated SourceLink
  * Switched to XUnit (it was just easier to configure for netcoreapp + paket)
  * Cleaned up fsproj files
  * Added explicit dependencies to [paket.template](https://github.com/Szer/FSharpx.Async/blob/b70de7dff2ac4e80075ad3b958bf19e19cd9c6fa/src/FSharpx.Async/paket.template#L23) file
  * A lot of small fixes in build scripts
  * The only place where I've changed source files are here (with conditional compilation):
    * [AsyncStream](https://github.com/Szer/FSharpx.Async/blob/6186137baf616a0702974c245d95851d950329ec/src/FSharpx.Async/AsyncStream.fs#L65)
    * [AsyncOperations](https://github.com/Szer/FSharpx.Async/blob/6186137baf616a0702974c245d95851d950329ec/src/FSharpx.Async/AsyncOperations.fs#L203)

### CODE REVIEW

**Comment by Szer** [comment]
Currently Travis fails only because it tries to test project with NUnit.

XUnit works fine from FAKE script:
image

**Comment by Szer** [comment]
Forgot that Ubuntu paths are case-sensitive :)
Now it builds everywhere

**Comment by panesofglass** [comment]
@fsprojectsgit or @forki, could you please merge this or #38?

**Comment by panesofglass** [comment]
@Szer, thank you for your PR, and apologies it has taken so long for someone to reply. I'd like to close this in favor of #38, though #38 needs some changes. Would you be interested in reworking your changes to build on top of #38?

**Comment by panesofglass** [comment]
Merged into #

**Pull request closed without merging**
