### PR TITLE
Add AsyncSeq.interleaveWith function

### PR DESCRIPTION
**Pull request by danielrbradley**
- Create basic set of tests around edge cases.
- Organise AsyncSeq tests into sub-modules per functions.

### CODE REVIEW

**Comment by danielrbradley** [comment]
Continuing conversation from previous thread:

from @eulerfx:

> I think a more appropriate name for this should be `interleave`. Merge as seen in `Observable.merge` for example, subscribes to the specified observables independently. In this implementation, `inputA` must produce a value before `inputB` is consumed. This means that one of the sequences can prevent the other one from being consumed.
> 
> Implementing a non-deterministic merge presents some challenges. Particularly because `Async` as is, doesn't easily support [non-deterministic choice](http://fssnip.net/8x). One could in theory use this in combination with `Async.Cache`.
> 
> One possible implementation which does not require these operation is:
> 
> ``` fsharp
>     let rec merge (a:AsyncSeq<'a>) (b:AsyncSeq<'a>) : AsyncSeq<'a> = asyncSeq {
>       use buffer = new System.Collections.Concurrent.BlockingCollection<_>(1)      
>       let rec reader (aseq:AsyncSeq<'a>) = async {
>         let! a = aseq
>         match a with
>         | Nil -> return ()
>         | Cons (h,t) ->
>           buffer.Add h
>           return! (reader t) }
>       Async.Start <| async {
>         do! Async.Parallel [| reader a ; reader b |] |> Async.Ignore
>         buffer.CompleteAdding() }
>       yield! buffer.GetConsumingEnumerable() |> ofSeq }
> ```
> 
> Note however the use of `BlockingCollection` meaning the readers of the individual streams may block, as well as the resulting sequence. This can result in deadlocks in some scenarios.
> 
> Take a look at how Hopac does [merge](https://github.com/Hopac/Hopac/blob/master/Docs/Inverting.md).

I had a quick look at your interleave implementation, I can see some similarities, the essential difference is that rather than just alternating between the left and right source, the choice is delegated to the comparer. 

On the issue of non-determinism of consumption - this function states the assumption that the two input seqences must be ordered - I'm seeing this as a feature rather than an issue as it will only consume the next items if required. 

As a practical example of where I'm using this - I'm representing event streams as sequences which are potentially too big to fit in memory, therefore, I use AsyncSeq to load them on the fly from an external store. This merge function is used when wanting to project from the combination of several independent sources, merging the events so they remain in order based on their timestamps. 

Indeed I've taken the name from the observable library - because I would use this in much the same way, the main difference being that the Observable.merge is performing the operation on a live stream, whereas I'm performing the merge on a replayed stream.

Don't know if that clarifies any of your questions or if I'm misunderstanding what you were trying to raise?

**Comment by eulerfx** [comment]
My only concern is with naming - should this ordered, lock-step merge be called `merge` or `interleave`? If merge, then what should be the name of the function which does not rely on order (as shown in the example above)? Initially, I also used `merge` rather than `interleave` and then went on to call the non-deterministic merge `mergeFair` but not sure that makes it as clear.

**Comment by danielrbradley** [comment]
Ah right I see what you're saying - merge doesn't imply ordered - so might be expected to do something like:

``` fsharp
    merge [ 1; 2 ] [ 2; 3; ] // [ 1; 2; 3; ]
```

I think the interleaved name implies exactly what you've already got - it's like a zip except that it alternates the items rather than pairing them. 

Perhaps something like sequentialMerge would help differentiate?

**Comment by danielrbradley** [comment]
Just to chuck the ideas out there - with help from the thesaurus ...
- merge
- interleave
- sequentialMerge
- lockstepMerge
- confluent
- interlace
- intermix
- knit
- correlate
- infuse

Keen to get this merged! Let me know if anyone wants to take a final call and I'll make the final tweak.

**Comment by eulerfx** [comment]
Maybe `compareMerge`? 

A few questions:
- Why not use a bool/int rather than a Choice for the compare function?
- The two initial inputs could be retrieved in parallel?
- Is it ok that the first items from the two sequences are selected without choice and the rest are chosen?

**Comment by forki** [comment]
can you please rebase this PR?

**Comment by dsyme** [comment]
How about `interleaveWith`.  `With` is commonly used in FSharp.Core as a suffix for things taking a comparer.

**Comment by eulerfx** [comment]
I like `interleaveWith`.

**Comment by danielrbradley** [comment]
:+1: for interleaveWith. Have renamed, rebased and squashed.

@eulerfx I've also changed it back to use an int comparer as that was how I did it on first pass too.

**Comment by eulerfx** [comment]
@danielrbradley would you rebase please

**Comment by vasily-kirichenko** [comment]
For naming inspiration see http://reactivex.io/documentation/operators.html#tree

**Comment by sideeffffect** [comment]
@danielrbradley  is this code still up-to-date and correct? can I help you with getting this merged?

**Comment by danielrbradley** [comment]
@sideeffffect completely forgot the PR still exists. Don't think it's up-to-date any more. Can rework it in the next couple of days if it's still wanted?

**Comment by panesofglass** [comment]
@danielrbradley, apologies for no one responding for so long. Yes, I would be happy to merge it if you want to get it updated.

**Comment by danielrbradley** [comment]
Wow, this is a blast from the past - not written .NET in a number of years! Doing some digging here it looks like AsyncSeq got merged into FSharp.Control.AsyncSeq and no longer exists in this project. 

It also looks like they added an [`interleaveChoice`](https://github.com/fsprojects/FSharp.Control.AsyncSeq/blob/master/src/FSharp.Control.AsyncSeq/AsyncSeq.fs#L1357) function which does a similar job to what I was proposing. 

@panesofglass I'd recommend closing this PR unless I've misunderstood where things are at now.

**Pull request closed without merging**
